[workspace]
members = [
    "node",
    "pallets/dao",
    "pallets/dao-collective",
    "pallets/dao-treasury",
    "pallets/membership",
    "pallets/dao-primitives",
    "pallets/treasury",
    "runtime",
]
[profile.release]
panic = "unwind"
