version: "3.2"

services:
  dev:
    container_name: societal-node
    image: paritytech/ci-linux:production
    working_dir: /var/www/societal-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/societal-node/.cargo
    volumes:
      - .:/var/www/societal-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/societal-node --dev --ws-external"
